### ISSUE TITLE
ambient gamma adjusting keeps oscillating up and down

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#196] opened 2021-02-12 15:11 UTC
clight, clightd master branch 12-2-2021

Instead of adjusting gamma to ambient brightness clight keeps oscillating up and down. I must switch to no mabient gamma.

[clight.log](https://github.com/FedeDP/Clight/files/5972621/clight.log)

**Comment by FedeDP** [comment] 2021-02-12 21:31
Hi! Thanks for opening this issue.
I cannot reproduce it here! Can you share a verbose log that starts with ambient_gamma enabled?
That one is not verbose and it has
> * Ambient gamma:		Disabled

as starting conf (i assume you changed it at runtime with clight-gui).

**Comment by promeneur** [comment] 2021-02-12 22:41
>> it has ambient gamma disable

No, the log is the record of:

start with no ambient gamma
switch to ambient gamma
you see 2 groups of oscillations
switch to no ambient gamma

**Comment by NICHOLAS85** [comment] 2021-02-12 23:01
Do you have multiple monitors?

**Comment by NICHOLAS85** [comment] 2021-02-12 23:04
Additionally, according to your log `Ambient Gamma` is disabled. Make sure it's enabled in your config and that clight-gui isn't turning it off(if you use the gui). If it's not your config or clight-gui then there might be another bug present

**Comment by promeneur** [comment] 2021-02-12 23:06
One monitor

**Comment by promeneur** [comment] 2021-02-12 23:09
i use clight-gui to switch on/off abient gamma

**Comment by FedeDP** [comment] 2021-02-12 23:33
I need a verbose log :) thank you!

**Comment by NICHOLAS85** [comment] 2021-02-12 23:49
What DE do you use?

**Comment by promeneur** [comment] 2021-02-13 08:41
I use KDE.

**Comment by promeneur** [comment] 2021-02-13 12:54
[clight.log](https://github.com/FedeDP/Clight/files/5975675/clight.log)

[clight.conf.txt](https://github.com/FedeDP/Clight/files/5975677/clight.conf.txt)

The ambient brightness is almost constant.

The temperature keeps oscillating between 4100 K and about 6000 K

**Comment by FedeDP** [comment] 2021-02-13 13:18
From your log, it seems it is working fine. 
You are seeing the issue because of #190: dimmer is not actually dimming your screen, thus you see a normal backlight with a 4100 temperature.
Instead, you should see a backlight level of 20% with 4100 gamma temp.
We can safely close this one, and focus on fixing other issue!

**Closed by FedeDP** 2021-02-13 13:18 UTC
Labels: next_rel
