### ISSUE TITLE
[BUG] High CPU usage in certain circumstances

### ISSUE THREAD

**Issue by yochananmarqos** [FedeDP/Clight#106] opened 2019-11-26 17:44 UTC
**Clight version the issue has been seen with:**
> 4.0

**Used distribution:**
> Manjaro GNOME

**Describe the bug**
A few things:
* At the top of the log, it says:
```
(W)[10:32:14]{opts.c:194}	SCREEN forcefully disabled as Clightd was built without screen support.
```
Is there a missing Cmake flag in the PKGBUILD?

* When I start my laptop (Dell Inspiron 5575) on battery power, the `clight` process uses a lot of CPU and no log is generated. If I kill `clight`, restart the `clightd.service` and start `clight` again, everything is fine.

* When keyboard backlight calibration is on, the backlight does not come on at all in the dark. It kind of defeats the purpose of having a keyboard backlight.

* When dpms is enabled, the screen turns of while watching a full-screen video. I use SMPlayer.

**Expected behavior**
Self-explanatory.

**To Reproduce**
Normal use.

[clight.log](https://pastebin.com/5LB9KdLv)

**Comment by FedeDP** [comment] 2019-11-26 18:45
Hi! Thanks for reporting these issues!
> At the top of the log, it says:

Fixed in Clightd 4.0-2 (https://aur.archlinux.org/packages/clightd/). Thanks!

> When dpms is enabled, the screen turns of while watching a full-screen video. I use SMPlayer.

SMplayer uses mpv as backend. Unfortunately org.freedesktop.ScreenSaver support is broken in mpv at the moment. I have the same issue. I just right click on clight desktop file and select "Pause backlight calibration"; or you can use eg: vlc!
Hopefully it will be fixed soon. 

> When keyboard backlight calibration is on, the backlight does not come on at all in the dark. It kind of defeats the purpose of having a keyboard backlight.

This is weird! Can you report here output of: `busctl call org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight GetMaxBrightness` ? Thanks!

> When I start my laptop (Dell Inspiron 5575) on battery power, the clight process uses a lot of CPU and no log is generated. If I kill clight, restart the clightd.service and start clight again, everything is fine. 

This is weird; i cannot reproduce it here. Your log seems fine.
Can you paste here a log from a clight fault run?

**Comment by yochananmarqos** [comment] 2019-11-26 19:35
> Fixed in Clightd 4.0-2 (https://aur.archlinux.org/packages/clightd/).
Aha! I thought there was a Cmake flag missing. 😄️ Thanks!

> output of: `busctl call org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight GetMaxBrightness`
`i 2`

I re-enabled keyboard backlight calibration and I'll see if I can catch something abnormal in the log.

**Comment by FedeDP** [comment] 2019-11-26 20:41
Note how kbd backlight is set to (1.0 - backlight_level) * max_kbd_backlight (in your case 2): https://github.com/FedeDP/Clight/blob/master/src/modules/backlight.c#L268.
Moreover, it is rounded to nearest integer, thus it should be set to "2" on low ambient brightness, ie: your maximum!

Let me know about the other issue too! Thanks!

**Comment by NICHOLAS85** [comment] 2019-11-26 21:13
I’ve also experienced the issue with the clight process using a lot of cpu a couple times. I haven’t been able to pinpoint when this occurs or what causes it, I usually only notice once I feel my laptop warming up abnormally. Killing and starting the clight process fixes this. I’ll leave on the verbose setting and attempt to share the log the next time this occurs.

**Comment by FedeDP** [comment] 2019-11-26 21:24
Great, thanks for joining! I have been using clight devel for months and it didn't occur here, or I didn't notice...

**Comment by NICHOLAS85** [comment] 2019-11-26 21:46
Here’s a link to my current config file:
https://raw.githubusercontent.com/NICHOLAS85/dotfiles/4c9a2719a60ce691f4350fea735c10743830382e/.config/clight.conf

**Comment by yochananmarqos** [comment] 2019-11-27 00:23
Here's my [`clight.conf`](https://pastebin.com/qhb7zM06).

**Comment by yochananmarqos** [comment] 2019-11-27 04:16
I noticed a webcam error in my journal after rebooting:
```
Nov 26 20:44:36 inspirognome kernel: uvcvideo: Failed to query (SET_CUR) UVC control 10 on unit 2: -32 (exp. 2).
Nov 26 20:44:36 inspirognome kernel: uvcvideo: Failed to query (SET_CUR) UVC control 4 on unit 1: -32 (exp. 4).
```

Only one error in the `clight.log`:
```
(D)[20:44:36]{bus.c:279}	get_screen_brightness(): Input/output error
```

**Comment by FedeDP** [comment] 2019-11-27 08:11
> Here’s a link to my current config file:

> Here's my clight.conf.

You both have dimmer dpms and gamma disabled. I will try with this config if i can reproduce the issue!

> I noticed a webcam error in my journal after rebooting:

That should not be an issue.

> Only one error in the clight.log:

This is interesting. It seems that XGetImage() fails here: https://github.com/FedeDP/Clightd/blob/master/src/modules/screen.c#L95.

**Comment by yochananmarqos** [comment] 2019-11-28 02:57
I can't reproduce the issue with the keyboard backlight now. Maybe it was a fluke or kernel 5.4 fixed it. It fixed not being able to resume from suspend, so you never know. ¯\\\_(ツ)_/¯

**Comment by FedeDP** [comment] 2019-11-28 07:34
Let's focus on high cpu bug then!

**Comment by NICHOLAS85** [comment] 2019-11-30 08:36
[clight.log](https://github.com/FedeDP/Clight/files/3906899/clight.log)
The high cpu bug has occurred again, attached is a log. Some info is I recently rebooted. Additionally, I built clightd with SCREEN support but this log states it was built without at the top. After restarting clight that message at the top dissapears.

**Comment by FedeDP** [comment] 2019-11-30 09:41
Mmmh I can't see anything wrong there. Is clightd.service enabled?

**Comment by NICHOLAS85** [comment] 2019-11-30 10:21
Yes, heres an output
```
$ systemctl status clightd
● clightd.service - Bus service to manage various screen related properties (gamma, dpms, backlight)
   Loaded: loaded (/lib/systemd/system/clightd.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-11-30 03:21:47 EST; 1h 58min ago
 Main PID: 12989 (clightd)
   Memory: 3.0M
   CGroup: /system.slice/clightd.service
           └─12989 /usr/lib/clightd/clightd

Nov 30 03:21:47 Nicks-Laptop systemd[1]: Starting Bus service to manage various screen related properties (gamma, dpms, backlight)...
Nov 30 03:21:47 Nicks-Laptop clightd[12989]: Registered Als sensor.
Nov 30 03:21:47 Nicks-Laptop clightd[12989]: (watch_displays_using_udev) Starting
Nov 30 03:21:47 Nicks-Laptop clightd[12989]: Registered Camera sensor.
Nov 30 03:21:47 Nicks-Laptop systemd[1]: Started Bus service to manage various screen related properties (gamma, dpms, backlight).
```

**Comment by FedeDP** [comment] 2019-11-30 13:16
It seems disabled though:
`Loaded: loaded (/lib/systemd/system/clightd.service; **disabled**; vendor preset: enabled)`

Btw stil unable to reproduce it here unfortunately, even with your configs :(

**Comment by yochananmarqos** [comment] 2019-11-30 15:57
Here's a log where the keyboard backlight did not come on in a dark room and and it did not adjust the backlight at all.
[clight.log](https://del.dog/ymekikanex.txt)

**Comment by FedeDP** [comment] 2019-11-30 18:16
> (D)[20:03:08]{bus.c:279}	get_screen_brightness(): Input/output error
(D)[20:03:08]{timer.c:40}	Disarmed timerfd on fd 25.
(D)[20:03:09]{backlight.c:317}	Average frames brightness: 0.000000.
(I)[20:03:09]{backlight.c:252}	Ambient brightness: 0.000. Clogged capture detected.

It seems like Clightd is not working well here: SCREEN module is failing to retrieve screen brightness and webcam captures return 0.00000 ambient brightness.
Consequently, Clight treats 0.0000 value as clogged capture and keyboard backlight is not touched (neither is screen backlight).

I always though 0.0000 was an impossible number for ambient brightness...is your room *this* dark? I think Clightd is misbehaving here...

**Comment by yochananmarqos** [comment] 2019-11-30 18:31
Yes, it was very dark. I was watching videos at night. I just updated to kernel 5.4.1, I'll see if there's any change tonight.

**Comment by yochananmarqos** [comment] 2019-12-01 03:16
The log was the same tonight, but I caught it chewing on the CPU again. When it happens, it stops logging.

The `uvcvideo` errors in the journal have to have something to do with it as it wasn't happening before v4.0.

**Comment by FedeDP** [comment] 2019-12-02 10:08
> Yes, it was very dark. I was watching videos at night. I just updated to kernel 5.4.1, I'll see if there's any change tonight.

Still i think that 0.00000 is an unreachable value...the issue itself can be quickly fixed (i should just set shutter_threshold default value to < 0 when conf option is commented), i'd like to understand if it is a normal value (if you can reproduce the "0.00000" ambient brightness it would be great!). 
May be it is just you webcam's quirk :)

> The log was the same tonight, but I caught it chewing on the CPU again. When it happens, it stops logging.

Interesting! I was not able to reproduce it yet. 
Are you sure it is Clight and not Clightd that is using CPU? Did something happened before (eg: system was resumed from suspend...)?

> The uvcvideo errors in the journal have to have something to do with it as it wasn't happening before v4.0.

It is because Clightd is now always resetting webcam default values before capturing to avoid captures with different parameters!
It the webcam still when those errors appear in dmesg? Can you check with any application?

**Comment by NICHOLAS85** [comment] 2019-12-02 20:23
@FedeDP, sorry for the late response. It is true clightd was somehow disabled at some point but still functioning. I've re-enabled it for now and will continue to try to narrow down the environment causing clight to get stuck using high cpu. I can also confirm that the process is clight and not clightd which has this CPU problem. I believe I've noticed it happening most after wakes from hibernation, but not 100% of the time.

**Comment by FedeDP** [comment] 2019-12-03 09:52
>  I've re-enabled it for now and will continue to try to narrow down the environment causing clight to get stuck using high cpu.

Thank you very much!

> I can also confirm that the process is clight and not clightd which has this CPU problem.

Great information, thanks.

> I believe I've noticed it happening most after wakes from hibernation, but not 100% of the time.

That is unfortunate...my laptop does not support hibernation very well thus i would not be able to test it...

**Comment by FedeDP** [comment] 2019-12-16 09:06
Any news on this topic?
I am really willing to kill this bug! :)

**Comment by yochananmarqos** [comment] 2019-12-16 19:59
The high CPU issue hasn't resurfaced at all for me.

**Comment by FedeDP** [comment] 2019-12-17 11:06
That is great! But it still leaves us with some unresolved questions...

**Comment by NICHOLAS85** [comment] 2019-12-24 06:33
High CPU resurfaced once again, it had been quite a while since it last occured. I rebooted after updating many packages including my kernel and such. Noticed the high cpu shortly after the reboot.

Log attached: [clightlog.txt](https://github.com/FedeDP/Clight/files/3997416/clightlog.txt)

**Comment by FedeDP** [comment] 2019-12-24 14:03
Once more i can only see an unusual error about get_screen_brightness call.
Can you try to disable SCREEN module and see if issue does persist? 
Thank you and merry xmas!

**Comment by NICHOLAS85** [comment] 2019-12-26 04:34
I've set no_screen to true and I'll let you know if it occurs again. Merry Christmas!

**Comment by FedeDP** [comment] 2019-12-26 10:34
Great! Thank you very much for your efforts testing this bug!

Merry Xmas!!

**Comment by FedeDP** [comment] 2020-01-07 08:47
I recently pushed some fixes that hopefully will address this issue.
You can try to update clight-git and let me know if issue persists! Thanks!

Moreover,
> Here's a log where the keyboard backlight did not come on in a dark room and and it did not adjust the backlight at all.

Was fixed (now 0.0 is a correct and not discarded ambient brightness).

**Comment by yochananmarqos** [comment] 2020-01-08 00:35
@FedeDP Thanks, I'll try it out and let you know how it goes.

**Comment by NICHOLAS85** [comment] 2020-01-08 16:25
Happy New Year! Unfortunately, I have had the high cpu issue resurface after setting no_screen on the old build. Heres the new log: [clight.log](https://github.com/FedeDP/Clight/files/4036242/clight.log)
I will rebuild clight from source and reenable screen and see if the issue comes up again.

**Comment by FedeDP** [comment] 2020-01-08 21:47
That is unfortunate :(

> Heres the new log: clight.log

As always, it seems clean. 

>  I will rebuild clight from source and reenable screen and see if the issue comes up again.

Great, thank you! Happy new year!

**Comment by yochananmarqos** [comment] 2020-01-09 02:11
It's working great with the git packages, the fix worked.

**Comment by FedeDP** [comment] 2020-01-09 18:34
> It's working great with the git packages, the fix worked.

Never say never :D i still hold my fingers crossed!

**Comment by FedeDP** [comment] 2020-01-20 10:46
Any news on this issue? :) Is it still working fine?

**Comment by NICHOLAS85** [comment] 2020-01-23 01:14
So far no issues!

**Comment by FedeDP** [comment] 2020-01-28 08:25
I am gonna close this one :)
Reopen it if any issue arises once more!

**Comment by NICHOLAS85** [comment] 2020-02-01 01:54
Ah! I've got some unfortunate news, it's popped up again. It's been almost a month since it last happened. I believe I turned off verbose mode so the following is all I could save from the log before I restarted the program. 

<details>
<summary>tail -f ~/.local/share/clight/clight.log </summary>

```
(I)[19:48:03]{main.c:134}       Clightd found, version: 4.1.
(I)[19:48:03]{main.c:164}       '/home/nicholas/.local/share/clight/modules.d/inhibit_bl_mod' loaded.
(I)[19:48:03]{upower.c:24}      Initial AC state: connected.
(W)[19:48:03]{interface.c:246}  Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
(I)[19:48:03]{interface.c:247}  Fallback at monitoring requests to org.freedesktop.ScreenSaver name owner.
(I)[19:48:07]{backlight.c:249}  Ambient brightness: 0.750 -> Backlight pct: 0.796.
(I)[20:03:09]{backlight.c:247}  Ambient brightness: 0.749 (-0.042 screen compensation) -> Backlight pct: 0.758.
(I)[20:18:10]{backlight.c:247}  Ambient brightness: 0.643 (-0.049 screen compensation) -> Backlight pct: 0.654.
(I)[20:33:10]{backlight.c:247}  Ambient brightness: 0.754 (-0.042 screen compensation) -> Backlight pct: 0.763.
(I)[20:48:11]{backlight.c:247}  Ambient brightness: 0.764 (-0.047 screen compensation) -> Backlight pct: 0.767.
```

</details>

**Comment by FedeDP** [comment] 2020-02-01 15:20
That is very unfortunate :(
Reopening!
Any more info? eg: uptime? It happened once more after a resume from hibernation?
Thank you!

**Comment by FedeDP** [comment] 2020-02-02 18:19
Wow it seems i finally manage to see this issue on my laptop! Right after a normal reboot.
I tried to attach with strace and this was the output:
{code}
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
epoll_wait(5, [{EPOLLIN|EPOLLHUP, {u32=1071955024, u64=94340028611664}}], 64, -1) = 1
^Cstrace: Process 726 detached
{code}
Ie: an infinite loop of epoll_wait... It seems like an fd is triggering an event that is not catched by clight. Going to further investigate!

**Comment by FedeDP** [comment] 2020-02-03 17:51
I just pushed a commit that adds a debug log in a couple of points that i think may lead to this bug, even if it would be really surprising if they would!

**Comment by NICHOLAS85** [comment] 2020-02-03 18:31
I've rebuilt clight, enabled verbose mode, and will be watching for this issue to occur again. Looks like we're getting closer to the core cause

**Comment by FedeDP** [comment] 2020-02-03 18:41
Great!

> Looks like we're getting closer to the core cause

Well, I assume the bug is either in BACKLIGHT, BUS, USERBUS or INTERFACE modules, as when running clight with other modules disabled, the bug was still present.
There is only one place in Clight where an event could theoretically go unread (thus looping generating the same event over and over), and that is when BACKLIGHT module gets "paused" by either an inhibition, or screen gets dimmed/dpmsed, or sensor goes missing.
In that case, it should gracefully stop polling deregistering its fd; i think the issue may lay in here. Ie: BACKLIGHT does not properly deregisters its fd; even if it sound unbelievable to me, that is my main target right now!
Let's hope the issue arises as quickly as possible!

**Comment by FedeDP** [comment] 2020-02-04 07:46
One more, most probable, idea:
While a message is waiting on BACKLIGHT queue (eg: DIMMER tells BACKLIGHT to pause as screen is dimmed). a timer event from its fd is triggered, and it is enqueued.
During next epoll call, we will receive dimmer message that tells BACKLIGHT to pause, causing it to deregister its fd and stop managing it; *but its timer event is still enqueued!* Thus it still generates events that nobody manages.

I have to understand whether this is a bug on clight or libmodule :)

**Comment by FedeDP** [comment] 2020-04-14 20:07
Has the bug resurfaced for anyone?

**Comment by yochananmarqos** [comment] 2020-04-14 20:09
"Not I", said the fly.

**Comment by NICHOLAS85** [comment] 2020-04-14 20:14
I have had this occur once. Unfortunately, it was while I was basically reinstalling my system and hadn't reconfigured Clight to use verbose logs and I didn't have time to note what was causing it. I remember I was compiling some software when I noticed.

**Comment by FedeDP** [comment] 2020-04-14 20:31
> I remember I was compiling some software when I noticed.

Very unfortunate; when did this happen? Ie: 2 months ago or a week ago? 
I never saw it occurring on my laptop again.

**Comment by NICHOLAS85** [comment] 2020-04-15 00:46
This happened in the last week.

**Comment by finkrer** [comment] 2020-06-04 10:48
What can I share to help resolve this?

**Comment by FedeDP** [comment] 2020-06-04 11:03
Unfortunately the bug is really hard to understand and consequently fix.
Right now clight git master is quite unstable; i will hopefully fix stability issues in the next days; then i will go back to this issue to fix it before 4.1 release.

It seems like a timed event is continuously arising and nobody manages it.
You can attach your verbose log file when it happens again, thank you!

**Comment by FedeDP** [comment] 2020-06-06 12:58
@finkrer Hi! In latest commits i tried to fix this issue; can you test with latest master?

Please note that i am not sure what is causing this issue; it is just a guess.
If the issue persists, it would be great if you could try to run clight with backlight module disabled to check if issue is caused by it.
Thank you!

**Comment by finkrer** [comment] 2020-06-06 16:13
I am now running the latest git version in verbose mode, if the issue occurs again I'll be sure to report it.

**Comment by FedeDP** [comment] 2020-06-06 17:31
Great! Thank you!

**Comment by FedeDP** [comment] 2020-06-18 12:41
Any news on this? :)

**Comment by finkrer** [comment] 2020-06-18 23:06
No news is good news in this case.

I didn't want to be too hasty in saying it's been fixed, but the issue hasn't reoccurred so far.
My laptop heats up a lot when it happens, so I would notice.

**Comment by NICHOLAS85** [comment] 2020-06-18 23:53
I have had this issue occur exactly once since the last time I reported experiencing a problem (over a month ago). Unfortunately, I was not in a position to collect any diagnostic data and forgot to keep tabs on what commit I was using. This is quite a rare issue. Is the log the only useful data I can provide when this happens?

**Comment by FedeDP** [comment] 2020-06-19 09:27
> This is quite a rare issue. Is the log the only useful data I can provide when this happens?

Unfortunately even log is quite useless...the only really useful output is strace's one (https://github.com/FedeDP/Clight/issues/106#issuecomment-581162209), but there are so many levels of possibilities that is practically impossible being sure to fix this.
Hopefully, latest clight-git has a proper fix (3963ffc33b9b54a1755e0f2fb696efd36163b791 commit), or at least it tries to fix what i guess can be our issue here.

**Comment by FedeDP** [comment] 2020-06-19 09:28
By the way thanks for your continuous testing!

**Comment by NICHOLAS85** [comment] 2020-06-20 03:37
Wow crazy timing. Just rebooted and had the issue occur. Here's a log and strace:
[clight.log.txt](https://github.com/FedeDP/Clight/files/4807315/clight.log.txt)
[clightstrace.txt](https://github.com/FedeDP/Clight/files/4807316/clightstrace.txt)
Those lines repeated infinitely for the strace.

**Comment by FedeDP** [comment] 2020-06-20 13:39
That's sad...is this with latest clight-git?
Unfortunately strace output is the same i got months ago; it seems like libmodule's loop continuously thinks some data is available to read.

The only thing i could do is to avoid using libmodule's internal loop and roll my own instead; then add a DEBUG() log to understand which fd is causing these wakeups.
I will probably push this on a new branch to let you test, if you are willing to do so :)

Thank you, i'll post again when the branch is ready!

**Comment by NICHOLAS85** [comment] 2020-06-20 18:56
Yes this occurred with the latest Clight-git (767e184) unfortunately. Only errors from the logs I’ve been able to see are `get_screen_brightness(): Input/output error` and a `capture_frames_brightness(): Device or resource busy`. I believe this has happened consistently after waking from hibernation or post reboot. Maybe there’s an issue with how these programs resume/startup. Maybe an error in my system causing a bug to manifest in Clight. 🤷‍♂️

**Comment by FedeDP** [comment] 2020-06-22 08:09
> I believe this has happened consistently after waking from hibernation or post reboot.

Yup it is not an issue; ie: it means that Clight is restarted before your webcam/screen is properly restarted, thus it may fail to eg: change gamma temperature/get screen brightness/use webcam.

> Yes this occurred with the latest Clight-git (767e184) unfortunately. 

That is very unfortunate :(

**Comment by finkrer** [comment] 2020-07-09 04:54
![image](https://user-images.githubusercontent.com/22712590/86997781-58767680-c1c8-11ea-8fe2-3b0c7b90d873.png)
Oh no, here it is again.

The log looks like [this](https://gist.github.com/finkrer/9f99c78c18342687c7455d6f7dba9026).

**Comment by FedeDP** [comment] 2020-07-09 06:46
Unfortunately once more nothing is shown in there :(

I am currently unable to fix it anytime soon, as i was hit by that like 2 times in 6 months; i will probably release clight 4.1 soon, even if this bug persists, as it is too rare to block a release with so many improvements and bugfixes.

After that, i will hopefully find the time to carry on libmodule 6.0.0 (https://github.com/FedeDP/libmodule/tree/devel) and consequently clight + clightd porting to new API.
Finally, i really hope that new libmodule can fix it, as i am starting to think that this issue is a bug from libmodule indeed.

**Comment by FedeDP** [comment] 2020-12-20 10:47
Hi everyone!
libmodule 5.0.1 was released; it contains a really small yet important fix on epoll loop error management. 
I don't really know if that will fix this issue but it was worth a try.
Let me know if issue arises again with libmodule 5.0.1!

**Comment by finkrer** [comment] 2021-01-06 10:09
libmodule 5.0.1-1, clight 4.2-2, clightd 5.1-1.

Still there unfortunately.

**Comment by NICHOLAS85** [comment] 2021-01-09 21:39
Just got hit with it again after months unfortunately with the latest commits as of today.
https://github.com/FedeDP/Clight/commit/b44c1e10e04af9968febd5fb2cc86188c378e562
https://github.com/FedeDP/libmodule/commit/3f60063e98631ce3fd25f70428b67ef15025597f

**Comment by FedeDP** [comment] 2021-01-09 21:45
Sigh 😔 that was worth a try.
I am currently back at working on libmodule 6.0.0 that will bring loooots of changes and improvements.
Hopefully it will fix this too.
It feels bad being unable to fix this; i could add some debug print here and there but it takes so much time waiting on issue to appear that I fear it would be pretty useless.

**Comment by tduboys** [comment] 2021-01-17 21:42
Hi all,
I just installed Arch on a new desktop hardware, and got the CPU-load error with libmodule 5.0.1-1, clight 4.2-2, clightd 5.1-1.

the only error I see on logs is : `(D)[22:36:12]{bus.c:175}        set_backlight_level(): Connection timed out`
I disabled screen module because I got this error on loop. Since, I got it only once, but didnt change the CPU-load issue.
If there is someone I can do for help on this issue, please ask

I never had issue with clight on other installs.

**Comment by promeneur** [comment] 2021-02-12 11:59
Clight and clightd master branch 12/2/2021
openSuse 15.2

Each time I start clight, after a delay it consumes 100 % of one core. I must terminate clight. I can't use clight.

No problem with package clight 4.2 and clightd 5.1.

**Comment by FedeDP** [comment] 2021-02-12 12:05
It this 100% reproducible? Does it happen every time?
(i obviously am not able to reproduce it, it's working here)

**Comment by promeneur** [comment] 2021-02-12 12:33
It's a random phenomenon.

No problem for 20 mn.

**Comment by promeneur** [comment] 2021-02-13 10:29
Again this morning.
After 3 h without any problem
Just (about 20 s) before dimmer switch off the screen (I get a black screen after 5 mn)

**Comment by FedeDP** [comment] 2021-02-13 11:20
>  Just (about 20 s) before dimmer switch off the screen (I get a black screen after 5 mn)

I don't think that's the root cause; anyway thank you very much! You are getting hitted by lots of weird bugs, i am sorry.
I pushed a new commit that should help tracking the module that is causing the high cpu usage. Can you upgrade clight?
Hopefully, as you are hit often, we will be able to track this down!

**Comment by promeneur** [comment] 2021-02-13 11:28
I updated yesterday. Is there a new master branch version  today ?

**Comment by FedeDP** [comment] 2021-02-13 11:34
Just pushed!

**Comment by FedeDP** [comment] 2021-02-15 20:45
To everyone: i recently added some more debug logs that should greatly help finding the root cause; i am optimist that we can fix this!
If you get hit by the bug, before killing clight, please do something like:
```
busctl --user set-property org.clight.clight /org/clight/clight/Conf org.clight.clight.Conf Verbose "b" true
```
Then wait some seconds and finally kill clight.
Then please share the log with me!
Thank you very much!

**Comment by FedeDP** [comment] 2021-02-19 17:43
User @NICHOLAS85 got it by this with new clight master. I can now tell that the issue comes from "Inhibit" dbus monitor that seems to get crazy and continuously report monitor fd as readable.
I added a new DEBUG print; it would be of great help if you all could upgrade to new clight master. Thank you!

**Comment by promeneur** [comment] 2021-02-20 19:38
3 mn => 560 MB log !

i give you an extract : the beginning and the end.

[clight_extract.log](https://github.com/FedeDP/Clight/files/6016213/clight_extract.log)

The problem occurs at the same time there were many disk accesses.

**Comment by FedeDP** [comment] 2021-02-20 19:43
@promeneur  yay!! Thank you very much! I will fix this bug finally O.O

**Comment by FedeDP** [comment] 2021-02-20 19:51
New git master should have a proper fix! 
I eagerly await for your tests! 
@promeneur you seem to get hit highly often, thus you are the better tester available :)
I'd give us a week of test, if no issue appear, this is fixed!
Moreover, please note that you will find a warn message "Connection reset by peer" in your logs if the issue would have been happened with old version.

It seems like the "inhibit" dbus monitor connection is closed by peer (ie: dbus server most probably;  not clight) for some reasons; and i was not actually checking the condition.
Now i will gracefully close my side of connection too, and open a new one to go on monitoring.

**Comment by FedeDP** [comment] 2021-02-25 19:35
This bug is (finally) fixed in latest Clight master!
Thanks to all of you, that greatly helped to debug it; really i appreciated every single minute you spent testing over and over, or just taking the time to chime in.
Thank you!

**Closed by FedeDP** 2021-02-25 19:35 UTC
Labels: bug
